name: Security Analysis

on:
  workflow_call:
    inputs:
      deps_cache_key:
        required: true
        type: string

jobs:
  security:
    name: Security Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: |
            out/
            cache/
            lib/
            node_modules/
          key: ${{ inputs.deps_cache_key }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: artifacts/

      - name: Copy build artifacts
        run: cp -r artifacts/out ./out

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Slither
        run: pip install slither-analyzer

      - name: Run Slither
        continue-on-error: true
        run: slither . --exclude-dependencies --json slither-report.json

      - name: Upload Slither findings
        uses: actions/upload-artifact@v4
        with:
          name: slither-report
          path: slither-report.json
          if-no-files-found: ignore 